Pathway
navgurukul/sansaar pull request #5
Opened 2020-08-17 17:00 UTC by pysaquib

Latest PR with following endpoints added: 
1. /courses/pathway/{pathwayId} - GET

2020-08-17 17:15 UTC, abhishekgupta92 commented on lib/migrations/20200816223510_change-course_categories.js
> +// eslint-disable-next-line
why is this file there if it has no relevant code?

2020-08-17 17:16 UTC, abhishekgupta92 commented on lib/migrations/20200816224454_change-course_categories-latest.js
> +  await knex.schema.createTable('main.course_categories', (table) => {
there are two files with main.course_categories create query. there should only be one.

2020-08-17 17:17 UTC, abhishekgupta92 commented on lib/services/courses.js
> +    return PathwayCourses.query().where('pathway_id', pathwayId).eager('courses');
eager is deprecated use withgraphfetched
check this link - https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched

2020-08-17 18:46 UTC, pysaquib commented on lib/migrations/20200816223510_change-course_categories.js
> +// eslint-disable-next-line
Issues in running migrations if this file is deleted.

2020-08-18 04:18 UTC, abhishekgupta92 commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +  // await knex.schema.createTable('main.course_categories', (table) => {
remove not needed comments from the pr

2020-08-18 04:18 UTC, abhishekgupta92 commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
>  exports.down = async (knex) => {};
'knex' is defined but never used

2020-08-18 04:18 UTC, abhishekgupta92 commented on lib/migrations/20200816223510_change-course_categories.js
> +// eslint-disable-next-line
then we should fix the issue :-)

2020-08-18 04:19 UTC, abhishekgupta92 commented on lib/services/courses.js
> +    return PathwayCourses.query().where('pathway_id', pathwayId).eager('courses');
@pysaquib still not done

2020-08-18 06:00 UTC, pysaquib commented on lib/migrations/20200816223510_change-course_categories.js
> +// eslint-disable-next-line
Done. Migration roll-backed and deleted the irrelevant file. Should run fine in fresh clones.

2020-08-18 17:43 UTC, abhishekgupta92 commented on lib/migrations/20200816223510_change-course_categories.js
> -exports.up = async (knex) => {
hey, still an empty file

2020-08-18 17:44 UTC, abhishekgupta92 commented on lib/routes/courses.js
> +      description: 'Update, remove, create courses in a pathway.',
Update the courses for a specific pathway ID

2020-08-18 17:46 UTC, abhishekgupta92 commented on lib/routes/courses.js
> +      description: 'Update, remove, create courses in a pathway.',
You just need to update the description.

2020-08-18 20:31 UTC, pysaquib commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
>  exports.down = async (knex) => {};
down function is still required even if we don't use it. Migrations won't run without it.

2020-08-18 20:34 UTC, pysaquib commented
Updated requested changes.

2020-08-31 02:34 UTC, RishabhVerma requested changes

2020-08-31 02:34 UTC, RishabhVerma commented on lib/migrations/20200816224454_change-course_categories-latest.js
>  exports.down = async (knex) => {};
The down part of migrations should always exist for rollback to happen.

2020-08-31 02:34 UTC, RishabhVerma commented on lib/models/pathwayCourses.js
> +      courseId: Joi.number().integer().greater(0),
We are using _ naming convention in column names at all the places. Check the other models.

2020-08-31 02:34 UTC, RishabhVerma commented on lib/routes/courses.js
> +        return coursesByPathwayId;
Display service should be used. Check Pralhad's PR to understand that.

2020-08-31 02:34 UTC, RishabhVerma commented on lib/services/pathway.js
> +          // eslint-disable-next-line
Yeh na karo! Bahot buri practice hai until absolutely needed. This is not a place where it should be done.

2020-08-31 02:34 UTC, RishabhVerma commented on lib/routes/courses.js
> +        return coursesByPathwayId;
Also, I remember seeing the response of this API. The response should ideally looked something like this.

```json
[
    {...random pathway course fields, "courses": [{}, {}, {...different objects of courses}]}, 
    {...random pathway course fields, "courses": [{}, {}, {...different objects of courses}]}, 
    {...random pathway course fields, "courses": [{}, {}, {...different objects of courses}]}, 
]
```

Ideally the response should be this.

```json
{
    "courses": [{}, {}, {}, {...different objects of courses}]
}
```

The FE is not supposed to deal with the internal reprsentation of pathway courses in the middle of pathways and courses. Secondly the relationship of pathways/courses should ideally be handled byh a ManyToMany relationship offered by objection. The insertion/deletion can all happen using that.

2020-08-31 02:34 UTC, RishabhVerma commented on lib/routes/courses.js
> +        return coursesService.updateCoursesByPathwayId(
This should not exist at the course service ideally but the pathway service. Secondly authenticaton is not the responsibility of any of the services. It is the responsibility of your routing layer. There should be no need to pass the user object to the service.

Thirdly it's a bad practice to directly pass objects to your service methods. We often forget what those objects are supposed to be comprised of in that way until using static typing. Always use parameters until objects are specifically needed or make sense.

2020-08-31 05:40 UTC, pysaquib commented on lib/migrations/20200816224454_change-course_categories-latest.js
>  exports.down = async (knex) => {};
Added down functions of migration. Only one left.

2020-08-31 12:28 UTC, pysaquib commented on lib/migrations/20200816224454_change-course_categories-latest.js
>  exports.down = async (knex) => {};
Done

2020-08-31 12:32 UTC, pysaquib commented on lib/models/pathwayCourses.js
> +      courseId: Joi.number().integer().greater(0),
Done

2020-09-01 06:47 UTC, pysaquib commented on lib/models/pathwayCourses.js
> +      courseId: Joi.number().integer().greater(0),
Done

2020-09-01 08:24 UTC, pysaquib commented on lib/migrations/20200816224454_change-course_categories-latest.js
>  exports.down = async (knex) => {};
All done

2020-09-01 08:38 UTC, pysaquib commented on lib/routes/courses.js
> +        return coursesByPathwayId;
Done

2020-09-01 08:38 UTC, pysaquib commented on lib/services/pathway.js
> +          // eslint-disable-next-line
Done

2020-09-01 08:39 UTC, pysaquib commented on lib/routes/courses.js
> +        return coursesService.updateCoursesByPathwayId(
Done

2020-09-02 06:35 UTC, RishabhVerma requested changes

2020-09-02 06:35 UTC, RishabhVerma commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +exports.down = async (knex) => {
You also need to drop `main.category`

2020-09-02 06:35 UTC, RishabhVerma commented on lib/models/pathwayCourses.js
> +      id: Joi.number().integer(),
id should always be required. all this should be required.

1. `course_id`
2. `pathway_id`

`updated_at` is not required.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/models/mentorTree.js
> -    /* eslint-enable global-require */
This line should exist.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/models/user.js
> -    /* eslint-enable global-require */
This line shouldn't be deleted.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/models/studentPathway.js
> -    /* eslint-enable global-require */
Needs to be enabled.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        scope: getRouteScope('admin'),
Why is this an authenticated role?

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        const pathwayCourses = await pathwayService.findCoursesByPathwayId(pathwayId);
`findCourses` is a better name.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        scope: getRouteScope('admin'),
Why is this admin?

2020-09-02 06:35 UTC, RishabhVerma commented on lib/services/pathway.js
> +    if (allPathwayCourses) {
if the course is already added into the pathway, this will add the course again.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/services/pathway.js
> +    const allPathwayCourses = await PathwayCourses.query().where('pathway_id', pathwayId);
Technically the structure should be something like this.

1. Delete the existing courses.
2. Make course objects.
3. Add the course objects just created.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +          course_id: PathwayCourses.field('course_id'),
This should be an array. `Joi.array().items(PathwayCourse.field('course_id'))`

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        return { pathwayCourse };
Display service is not used.

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        const pathwayCourse = await pathwayService.updateCoursesByPathwayId(
variable names can be better. 

`const courses = jo bhi code hai`

2020-09-02 06:35 UTC, RishabhVerma commented on lib/routes/pathways.js
> +        const pathwayCourse = await pathwayService.updateCoursesByPathwayId(
`updateCoursesByPathwayId` should be called `upsertCourses`

2020-09-02 06:35 UTC, RishabhVerma commented on lib/services/pathway.js
> +    const pathwayCourses = await PathwayCourses.query().where('pathway_id', pathwayId);
This should not be a query. But courses should exist as a relation on the pathway model and you can directly get courses from there.

2020-09-02 06:59 UTC, pysaquib commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +exports.down = async (knex) => {
Done

2020-09-02 07:00 UTC, pysaquib commented on lib/models/pathwayCourses.js
> +      id: Joi.number().integer(),
Done

2020-09-02 07:02 UTC, pysaquib commented on lib/models/studentPathway.js
> -    /* eslint-enable global-require */
Done

2020-09-02 07:03 UTC, pysaquib commented on lib/models/user.js
> -    /* eslint-enable global-require */
Done

2020-09-02 07:03 UTC, pysaquib commented on lib/models/mentorTree.js
> -    /* eslint-enable global-require */
Done

2020-09-02 07:26 UTC, pysaquib commented on lib/routes/pathways.js
> +          course_id: PathwayCourses.field('course_id'),
Done

2020-09-02 15:20 UTC, pysaquib commented on lib/services/pathway.js
> +    const allPathwayCourses = await PathwayCourses.query().where('pathway_id', pathwayId);
Done

2020-09-02 15:21 UTC, pysaquib commented on lib/routes/pathways.js
> +        const pathwayCourse = await pathwayService.updateCoursesByPathwayId(
Done

2020-09-02 19:31 UTC, pysaquib commented on lib/services/pathway.js
> +    const pathwayCourses = await PathwayCourses.query().where('pathway_id', pathwayId);
Done

2020-09-02 19:31 UTC, pysaquib commented on lib/routes/pathways.js
> +        return { pathwayCourse };
Done

2020-09-02 19:33 UTC, abhishekgupta92 commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +  await knex.schema.dropTable('main.caegories');
table name is wrong

2020-09-02 19:35 UTC, abhishekgupta92 commented on lib/routes/pathways.js
> +        scope: getRouteScope('admin'),
@pysaquib - this is still pending

2020-09-02 19:36 UTC, abhishekgupta92 commented on lib/routes/pathways.js
> +        scope: getRouteScope('admin'),
@pysaquib change role to an existing one. (find in code where existing roles are defined)

2020-09-02 19:37 UTC, pysaquib commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +  await knex.schema.dropTable('main.caegories');
Fixed already

2020-09-02 19:41 UTC, abhishekgupta92 commented on lib/migrations/20200816210347_course_pathway-category-course_categories.js
> +  await knex.schema.dropTable('main.caegories');
No. Check - https://github.com/navgurukul/sansaar/blob/pathway/lib/migrations/20200816210347_course_pathway-category-course_categories.js

Created table is category, and table being dropped is categories

2020-09-17 11:01 UTC, closed without merging