Courses api
navgurukul/sansaar pull request #6
Opened 2020-08-18 13:11 UTC by pralhad88

created four API for get exercise by slug, enrol in course, get course topic and get solution if exercise.

2020-08-18 17:57 UTC, abhishekgupta92 submitted a review, later dismissed

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/routes/courses.js
> +        const listOfTopic = await coursesService.getCourseTopics(courseId);
courseTopics is proper variable name here. function jaisa naam rakho. don't introduce new terms in general

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/routes/exercises.js
> +        const getExerciseBySlug = await exercisesService.getExerciseBySlug(slug, authUser);
you can simplify this by saying

const exercise = ...
return {exercise}

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/routes/exercises.js
> +      description: 'gets the solution by exercies Id.',
Properly write and format the description

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/services/courses.js
>          .eager({ courses: true })
don't use eager, it is deprecated use - withgraphsjoined

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/services/courses.js
> +    const listOfTopics = await Exercises.query(txn)
keep this variable as courseTopics, and return easily

2020-08-18 17:57 UTC, abhishekgupta92 commented on lib/services/courses.js
> +  }
in one cases we return alreadyEnrolled: true and in other we return enrolled: true
it can be designed better. 
i don't think we should check for course_id is valid or not. coz that's too much for this api

we simply upsert enrolment id and return {success:true} and error otherwise, that would be short and sufficient.

2020-08-19 12:05 UTC, pralhad88 commented on lib/routes/courses.js
> +        const listOfTopic = await coursesService.getCourseTopics(courseId);
Ok, getListOfTopic like that

2020-08-19 12:23 UTC, pralhad88 commented on lib/services/courses.js
> +  }
Ok

2020-08-31 02:23 UTC, RishabhVerma requested changes
### 1

@abhishekgupta92 Not checking the courseSeeder file as assuming the old code is working and changing it right now would be too much effort.

### 2

If we are going on a pathway based approach then why are we supporting course level enrolments still? The user service has two methods `addPathways` and `removePathways` which can signify enrolment in the pathways. This is also supported from within the admin panel. The API structure that might make more sense would be somehting like.

1. GET /pathways (gives both enrolled and available pathways)
2. GET /pathways/{pathwayId}/courses


### 3

JSON should eventually be returned by displayService until it is something which is very simplistic. The responsibility of fetching the required relationships from the DB should not be the responsibility of the specified service used to do heavy lifting but of the displayService available under `services/display` It isn't used anywhere in `/course/{courseId}/enroll`.

### 4
We are following a convention of using plurals in the API routes. That is not followed in the course.

### 5
Ideally all the course management endpoints should exist in a different file and the other endpoints related to interaction of users & courses in another one.

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/courses.js
> +  async getCourseTopics(courseId, txn = null) {
Two issues with this method.

1. It shouldn't be called getCourseTopics. If we are naming the model of the children entity of courses as exercises. It should be referred to as exercises everywhere. Not topics.

2. The more important issue - No method for this should exist. This should just exist as a relationship on the courses model. Objection supports this by default. And a seperate method for this cannot exist. In general I don't see usage of relationships at the ORM level in any of the code base related to courses. Objection is super powerful. Bahot saare heavylifting woh khud kar sakta hai :)

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/courses.js
> +  async enrollInCourse(courseId, authUser, txn = null) {
Need to rethink enrolments.

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/courses.js
> +  async findByCourseName(name, graphFetchRelation = '', txn) {
graphFetchRelation should be the responsibility of the display service.

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/exercises.js
> +  async getExerciseBySlug(slug, authUser, txn = null) {
Do we have any notion of submissions like the way it used to exist in the SARAL? Can we just remove it or move to the newer method? This API is not being made in a backward-compatible way as the current SARAL will keep on running for a while.

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/exercises.js
> +  async addUpdateExercise(details, txn) {
`upsertExercise` is a better name.

2020-08-31 02:23 UTC, RishabhVerma commented on lib/services/exercises.js
> +  async addUpdateExercise(details, txn) {
Not a deal breaker - in the ideal cases the upsertExercise and addUpdateChildExercise should be combined into one recursive function.

2020-08-31 05:54 UTC, pralhad88 commented on lib/config/index.js
> +      secret: process.env.SECRET_KEY,
GITHUB_SECRET_KEY is ok ?

2020-08-31 07:50 UTC, abhishekgupta92 commented
Yes

On Mon, Aug 31, 2020, 11:24 AM Pralhad Jadhav <notifications@github.com>
wrote:

> *@pralhad88* commented on this pull request.
> ------------------------------
>
> In lib/config/index.js
> <https://github.com/navgurukul/sansaar/pull/6#discussion_r479908309>:
>
> > @@ -11,6 +11,11 @@ module.exports = {
>        secret: process.env.AUTH_JWT_SECRET,
>        expiresIn: '7d',
>      },
> +    githubAccessKey: {
> +      secret: process.env.SECRET_KEY,
>
> GITHUB_SECRET_KEY is ok ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/navgurukul/sansaar/pull/6#discussion_r479908309>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAM2M4MZM4I2WW6SICW56SLSDM3LFANCNFSM4QDOHFCQ>
> .
>

2020-09-01 03:54 UTC, pralhad88 commented on lib/models/exercises.js
> -      id: Joi.number().integer().greater(0).required(),
When I try to insert new exercise at that time error is throwing id required that's why i removed required

2020-09-01 03:58 UTC, pralhad88 commented on lib/services/exercises.js
> +  async addUpdateExercise(details, txn) {
but here we are adding two type of exercise child and parent that's why i wrote separate function for adding childExercise

2020-09-04 20:24 UTC, pysaquib commented on lib/models/exercises.js
> -      id: Joi.number().integer().greater(0).required(),
@RishabhVerma This is what happened with pathway courses.

2020-09-07 21:14 UTC, pysaquib commented on lib/services/courses.js
> +  async getCourseTopics(courseId, txn = null) {
Done

2020-09-08 07:28 UTC, pysaquib commented on lib/services/courses.js
> +  async findByCourseName(name, graphFetchRelation = '', txn) {
graphFetched was not needed here, so removed.
Done.

2020-09-08 07:29 UTC, pysaquib commented on lib/services/exercises.js
> +  async getExerciseBySlug(slug, authUser, txn = null) {
Need discussion on this

2020-09-14 09:40 UTC, pysaquib commented on lib/models/enrollCourses.js
> +      id: Joi.number().integer().greater(0),
ids are auto increment. Keeping it required makes it compulsory to provide id in payloads.

2020-09-21 14:53 UTC, RishabhVerma requested changes

2020-09-21 14:53 UTC, RishabhVerma commented on .eslintrc.js
> +    camelcase: 0,
follow the convention followed in the file. `'camelcase'` should be in single quotes.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/config/index.js
> +      schoolId: process.env.SCHOOL_ID,
@pysaquib This is still not resolved.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/config/index.js
> +      basePath: process.env.BASE_URL,
Similarly this shold be called `GITHUB_BASE_URL`

2020-09-21 14:53 UTC, RishabhVerma commented on lib/migrations/20200830194458_alter_table_class_and_add_registration.js
> +    table.string('feedback', 255);
255 is too short a length for feedback. Can you figure out what is the field which can support long text? Ideally postgres should support some way which is better than specifying a max limit for a string.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/migrations/20200905124935_alter_classes_table.js
> +    table.string('class_type').after('title').notNullable();
Ideally this should be called `type` instead of `class_type`. The column exists inside the classes table. That pretty much signifies that it is class type.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/migrations/20200908170337_drop_submission_table.js
> +  await knex.schema.createTable('main.submissions', (table) => {
Why does a submissions table exist? Currently there is no notion of submissions.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/models/category.js
> +    return 'main.category';
Category is too generic a name for the table. There might be different kinds of categories. Better call it class categhory.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/models/category.js
> +      category_name: Joi.string().max(45).required(),
Column name should be only name.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/models/enrollCourse.js
> +      course_status: Joi.string(),
@pysaquib This comment is still not resolved.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/network/axios.js
> +const axiosAdmin = axios.create({
`axiosAdmin` and `axiosInstance` need to have better names. Ideally if they are not being used anywhere except the chat service they should be defined in the chat service itself. 

If they are defined outside you should create a directory called `helpers` inside `lib` to have them.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/routes/chatUsers.js
> +    path: '/chat/user/{userId}',
If the `GET` endpoints has the route `/chat/users` for the list of users then a single user's endpoint should be `/chat/users/{userId`.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/routes/chatUsers.js
> +          userId: Joi.string().pattern(/^@([a-z0-9])+:(navgurukul.org)$/),
If the user_id is being stored in the DB under the chat_id column, then you should have this pattern specified int hat model and just re-use that using Model.field over here.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/routes/chatUsers.js
> +    path: '/chat/user/create',
`POST /chat/users` is enough. Post in itself means creation.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/routes/users.js
> +    method: 'GET',
This is class related functionality. Should be a different file. Not in this file.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/services/classRegistrations.js
> +  async registerToClassById(registrationDetails) {
the methods of services in most of the cases should explicitly take parameters. `user_id` and `class_id` should be paramters.

2020-09-21 14:53 UTC, RishabhVerma commented on lib/services/classRegistrations.js
> +  async registerToClassById(registrationDetails) {
Class registration and class service should be one file only and not two different files. Services  are generally not made for different DB models but for human defined constructs in the code bases. So ideally all class related functionality should exist in a single class service.

2020-09-21 16:02 UTC, pysaquib commented on lib/routes/chatUsers.js
> +    path: '/chat/user/{userId}',
Yes.

2020-09-21 16:07 UTC, pysaquib commented on lib/routes/chatUsers.js
> +          userId: Joi.string().pattern(/^@([a-z0-9])+:(navgurukul.org)$/),
This one is to be ignored for now. Matrix userId pattern is this but while creating a user only username (without domain and all) is allowed in matrix.
In fact, this whole /chat route and chatService(except handleCommand service) should be ignored for now. We are going to do changes in it later.

2020-09-21 16:10 UTC, pysaquib commented on lib/routes/users.js
> +    method: 'GET',
There is a similar route in classes route which gives enrolled classes to an authenticated user.

This one was meant for dashboard admin only, where they can get any user's registered classes.
If it is not useful, it should be removed then?

2020-09-21 17:24 UTC, pysaquib commented on lib/routes/users.js
> +    method: 'GET',
In fact, there exists a duplicate route in /classes. Removed it from /user route

2020-09-21 19:35 UTC, pysaquib commented on lib/services/classRegistrations.js
> +  async registerToClassById(registrationDetails) {
1. Every service methods are taking parameters like you said, except services used in **POST** requests and services meant for fetchingGraph. This is a **POST** request and details of a registrations are being inserted in the table, so sending userId and classId along with the whole object made sense. Let me know if you want it the parameters to be `userId`, `classId`, `registrationDetails`.

2. Makes sense. Fixed

2020-09-21 19:37 UTC, pysaquib commented on lib/routes/exercises.js
>        auth: {
Removed mode : optional from here but keeping authentication optional in some routes (like /classes/upcoming) earlier it was supposed to work like it

2020-09-22 14:10 UTC, pysaquib commented on lib/models/enrollCourse.js
> +      course_status: Joi.string(),
What does course_status mean? Is it completed by a particular `student_id` ?

2020-09-22 14:10 UTC, pysaquib commented on lib/network/axios.js
> +const axiosAdmin = axios.create({
Moving them to /lib/helpers/network for abstraction.
Renaming them to axiosAuth and axiosUnAuth respectively...

2020-09-23 01:25 UTC, RishabhVerma requested changes

2020-09-23 01:25 UTC, RishabhVerma commented on lib/helpers/network/axios.js
> +const axiosAuth = axios.create({
The file path should ideally be `lib/helpers/chat.js`. axios.js is a generic name.

2020-09-23 01:25 UTC, RishabhVerma commented on lib/migrations/20200908170337_drop_submission_table.js
> +  await knex.schema.createTable('main.submissions', (table) => {
Makes sense. Resolvint his conversation.

2020-09-23 01:25 UTC, RishabhVerma commented on lib/models/enrollCourse.js
> +      course_status: Joi.string(),
You can check how it is being used across the codebase. It probably tracks if the course has been completed or not. In case it is not being used, you can remove the field.

2020-09-23 01:25 UTC, RishabhVerma commented on lib/routes/chatUsers.js
> +          userId: Joi.string().pattern(/^@([a-z0-9])+:(navgurukul.org)$/),
Okay. Got it.

2020-09-23 01:25 UTC, RishabhVerma commented on lib/services/chat.js
> +  /* eslint-disable */
We shouldn't use such a large eslint-disable block without a good reason. Please fix the code here.

2020-09-23 06:34 UTC, pysaquib commented on lib/services/courses.js
> +  async getCourseTopics(courseId, txn = null) {
Done

2020-09-23 06:40 UTC, pysaquib commented on lib/helpers/network/axios.js
> +const axiosAuth = axios.create({
Done

2020-09-24 03:09 UTC, RishabhVerma approved these changes

2020-09-24 03:10 UTC, merged